# Generated by Django 3.1.3 on 2021-02-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('silver', models.PositiveSmallIntegerField(default=0)),
                ('gold', models.PositiveSmallIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=5)),
                ('rank_progres', models.PositiveSmallIntegerField(default=0)),
                ('silver_required_for_rank', models.PositiveSmallIntegerField(default=10)),
                ('silver_total', models.PositiveSmallIntegerField(default=0)),
                ('silver_required_for_gold', models.PositiveSmallIntegerField(default=9)),
                ('adus_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.consumer')),
            ],
        ),
    ]
