# Generated by Django 3.1.3 on 2021-02-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='adus_de',
        ),
    ]
