# Generated by Django 3.1.3 on 2021-02-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_remove_consumer_adus_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='adus_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.consumer'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
