# Generated by Django 3.1.3 on 2021-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_consumer_friend_refferal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='friend_refferal',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='referral_code',
            field=models.CharField(default='waiting', max_length=8, unique=True),
        ),
    ]
