# Generated by Django 3.1.3 on 2021-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20210208_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='referral_code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
