# Generated by Django 3.1.3 on 2021-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_consumer_bar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='friends',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumer',
            name='gold_made_from_friends',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
