# Generated by Django 3.1.3 on 2021-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20210208_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='referral_code',
            field=models.CharField(default='nimic', max_length=8, unique=True),
        ),
    ]
