# Generated by Django 3.1.3 on 2021-02-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_auto_20210208_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='gived_one_gold',
            field=models.BooleanField(default=False),
        ),
    ]
