# Generated by Django 3.1.3 on 2021-02-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_consumer_gived_one_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='friend_refferal',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='referral_code',
            field=models.CharField(default='nimic', max_length=6, unique=True),
        ),
    ]
